[package]
name = "bluebrick-ttlego-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
ctor = "0.4.1"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
msgbox = "0.7.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60.0", features = ["Win32_UI_Input_XboxController"] }

[lib]
crate-type = ["cdylib", "lib"]
